<?php
require_once('database/constantes.inc.php');
require_once('database/connect.php');
require_once("database/user.php");
require_once("database/clothe.php");
require_once("database/category.php");
require_once("database/weather.php");
require_once("database/event.php");
require_once("functions.php");
require_once("meteoRecord.php");
require_once("week.php");
require_once("day.php");